# Generated by Django 5.1.7 on 2025-04-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('createdate', models.TimeField(auto_now_add=True)),
                ('telnumber', models.CharField(max_length=10)),
            ],
        ),
    ]
