# Generated by Django 5.1.7 on 2025-04-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watermodel',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default='20', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='watermodel',
            name='telnumber',
            field=models.CharField(max_length=13),
        ),
    ]
